version: "3.8"

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2023-08-16T20-17-30Z
    command:
      - server
      - /data
      - --console-address
      - :9090
    ports:
      - ${MINIO_API_PORT}:9000
      - ${MINIO_CONSOLE_PORT}:9090
    volumes:
      - ./minio-storage:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
